[versions]
androidGradlePlugin = "8.0.2"
dotsindicator = "5.0"
dragdropswipeRecyclerview = "1.1.1"
firebaseMessagingKtx = "23.2.1"
flexbox = "3.0.0"
googleServices = "4.3.15"
hiltAndroid = "2.47"
hiltAndroidx = "1.0.0"
jsoup = "1.16.1"
junitJupiterEngine = "5.10.0"
kapt = "1.8.22"
kotlin = "1.8.22"
lifecycleProcess = "2.6.1"
lottie = "6.1.0"
navigation = "2.6.0"
realmKotlin = "1.10.2"
sentryAndroidFragment = "6.28.0"
testRunner = "1.5.2"
webkit = "1.7.0"
workRuntimeKtx = "2.8.1"

[libraries]
dotsindicator = { module = "com.tbuonomo:dotsindicator", version.ref = "dotsindicator" }
dragdropswipe-recyclerview = { module = "com.ernestoyaquello.dragdropswiperecyclerview:drag-drop-swipe-recyclerview", version.ref = "dragdropswipeRecyclerview" }
firebase-messaging-ktx = { module = "com.google.firebase:firebase-messaging-ktx", version.ref = "firebaseMessagingKtx" }
flexbox = { module = "com.google.android.flexbox:flexbox", version.ref = "flexbox" }
google-services = { module = "com.google.gms:google-services", version.ref = "googleServices" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltAndroid" }
hilt-compiler-androidx = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltAndroidx" }
hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hiltAndroidx" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycleProcess" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
navigation-safeargs = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "navigation" }
realm-kotlin-base = { module = "io.realm.kotlin:library-base", version.ref = "realmKotlin" }
sentry-android-fragment = { module = "io.sentry:sentry-android-fragment", version.ref = "sentryAndroidFragment" }
webkit = { module = "androidx.webkit:webkit", version.ref = "webkit" }
work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
# Unit tests
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junitJupiterEngine" }
test-runner = { module = "androidx.test:runner", version.ref = "testRunner" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "hiltAndroid" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrains-kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kapt" }
realm-kotlin = { id = "io.realm.kotlin", version.ref = "realmKotlin" }
