[versions]
androidGradlePlugin = "8.8.2"
coilSvg = "2.7.0"
compose = "1.7.8" # Doesn't build when bumped (waiting for Android SDK 35)
desugarJDK = "2.1.5"
dotsindicator = "5.1.0"
dragDropSwipeRecyclerView = "1.0.0"
firebaseMessagingKtx = "24.1.1"
flexbox = "3.0.0"
googleServices = "4.4.2"
hiltAndroid = "2.56.2"
hiltAndroidx = "1.2.0"
jsoup = "1.20.1"
junit = "4.13.2"
junitVersion = "1.2.1"
kotlin = "2.0.21" # Keep the same version as the one in Core
ksp = "2.0.21-1.0.28" # Keep the same version as the one in Core
leakcanaryAndroid = "2.12"
lifecycleProcess = "2.8.7" # Waiting for SDK 35 to update to 2.9.0+
lottie = "6.6.6"
navigation = "2.8.9"
playServices = "18.7.0"
realmKotlin = "3.0.0"
richHtmlEditor = "0.2.0"
sentryAndroidFragment = "8.11.1" # TODO: Upgrade once SwissTransfer updates Sentry Gradle plugin past 5.5.0
webkit = "1.13.0"
workConcurrentFutures = "1.2.0"
workRuntimeKtx = "2.9.1" # Doesn't build when bumped (waiting for Android SDK 35)

[libraries]
coil-svg = { module = "io.coil-kt:coil-svg", version.ref = "coilSvg" }
compose-ui-android = { group = "androidx.compose.ui", name = "ui-android", version.ref = "compose" }
dotsindicator = { module = "com.tbuonomo:dotsindicator", version.ref = "dotsindicator" }
desugar-jdk = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugarJDK" }
dragdropswipe-recyclerview = { module = "com.github.infomaniak:DragDropSwipeRecyclerview", version.ref = "dragDropSwipeRecyclerView" }
firebase-messaging-ktx = { module = "com.google.firebase:firebase-messaging-ktx", version.ref = "firebaseMessagingKtx" }
flexbox = { module = "com.google.android.flexbox:flexbox", version.ref = "flexbox" }
google-services = { module = "com.google.gms:google-services", version.ref = "googleServices" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltAndroid" }
hilt-compiler-androidx = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltAndroidx" }
hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hiltAndroidx" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanaryAndroid" }
lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycleProcess" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
navigation-safeargs = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "navigation" }
play-services-base = { group = "com.google.android.gms", name = "play-services-base", version.ref = "playServices" }
realm-kotlin-base = { module = "io.realm.kotlin:library-base", version.ref = "realmKotlin" }
rich-html-editor = { module = "com.github.infomaniak:android-rich-html-editor", version.ref = "richHtmlEditor" }
sentry-android-fragment = { module = "io.sentry:sentry-android-fragment", version.ref = "sentryAndroidFragment" }
webkit = { module = "androidx.webkit:webkit", version.ref = "webkit" }
work-concurrent-futures = { module = "androidx.concurrent:concurrent-futures-ktx", version.ref = "workConcurrentFutures" }
work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
# Unit tests
ext-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
junit = { module = "junit:junit", version.ref = "junit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "hiltAndroid" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrains-kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
realm-kotlin = { id = "io.realm.kotlin", version.ref = "realmKotlin" }
